project:
  type: website

website:
  title: "KED2023"
  site-url: https://albert-rapp.de
  search: true
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - schedule.md
      - lectures.md
      - assignments.md
      - materials.md
    pinned: true
  page-footer:
    left: "Copyright 2023, Alex Flückiger"
    right:
      - icon: github
        href: https://github.com/aflueckiger/KED2023
  open-graph: true
  twitter-card:
    description: "In this hands-on seminar, "
    image: /_images/background.png
  favicon: /_images/favicon/android-chrome-512x512.png


format:
  html:
    theme:
     light: [litera, light_styles.scss]
     dark: [litera, dark_styles.scss]
    toc: true



